---
# Source: redis-ha/templates/redis-server-deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  # Pay attention to the redis-role label at runtime. The self-determination logic in the image sets this value accordingly.
  name: redis-ha-server
  labels:
    name: redis-ha-server
    redis-node: "true"
    app: redis-ha
    chart: redis-ha-2.2.3
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: redis-ha
        component: server
        name: redis-ha-server
        redis-node: "true"
    spec:
      serviceAccountName: default
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: redis-ha
                  component: server
              topologyKey: kubernetes.io/hostname
      containers:
      - name: redis
        image: quay.io/smile/redis:4.0.8r0
        resources:
          limits:
            memory: 700Mi
          requests:
            cpu: 100m
            memory: 200Mi
          
        env:
          - name: REDIS_SENTINEL_SERVICE_HOST
            value: "redis-sentinel"
          - name: REDIS_CHART_PREFIX
            value: redis-ha-
        ports:
          - containerPort: 6379
        volumeMounts:
          - mountPath: /redis-master-data
            name: data
      volumes:
      - name: data

