---
# Source: redis-ha/templates/redis-slave-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: redis-ha-slave-svc
  labels:
    role: service
    app: redis-ha
    chart: redis-ha-2.2.3
  annotations:
    {}
    
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis-ha
    redis-node: "true"
    redis-role: "slave"
  type: "ClusterIP"
