version: '3'
services:
    grails-crud:
        build:
            context: .
        container_name: grails-crud
        image: grails-crud
        environment:
            - NODE_ENV=development
        ports:
            - 8080:8080
        depends_on:
            - mongo
#            - memcached
    mongo:
        image: mongo:3.4.17
        container_name: mongodb
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet
#    memcached:
#        image: bitnami/memcached:latest
#        container_name: memcached
#        ports:
#            - 11211:11211
#    crud-test:
#        build:
#            context: .
#        command: gradle test-app -integration
#        depends_on:
#        - mongo
#        - memcached
